### ISSUE TITLE
Deserialization of ancient C structs

### ISSUE THREAD

**Issue by winterheart** [felixguendling/cista#103]
Hello.

I have ancient C project with structs like this:

```
typedef struct {
    uint8_t *bits;
    uint8_t type;
    int16_t w;
    int16_t h;
} Bitmap;

typedef struct {
    int16_t x1;
    int16_t y1;
    int16_t x2;
    int16_t y2;
} Rect;

typedef struct {
    Bitmap bm;
    union {
        Rect updateArea;
        Rect anchorArea;
    };
    int32_t palette;
} Frame;
```

I have serialized binary files which I need to read, but they are produced by a 32-bit tool where pointers equals 4 bytes. So I need to correctly initialize a 32-bit pointer from the `Bitmap` struct which points to binary data that follows directly after a serialized struct (like `ptr = *Frame + 1`). How can I implement this with Cista++?

**Comment by felixguendling** [comment]
If you want to use a 64bit build now but have 32bit serialized binary data, the binary layout will be totally different (due to aligment not only the pointer width changes but also the struct size, internal padding bytes, etc.). You could try using a 32bit `cista::offset_ptr` type and initialize the value with the correct offset (relative to the `this` pointer of the `offset_ptr`). Maybe you have to used packed structs for this to work.

If you want to use a 32bit build now to read your 32bit serialized binary data, the binary layout is the same which makes it a bit easier. Then, you can try something like this: https://wandbox.org/permlink/Sg2E7m87cjR6wKON

But I'm not sure, whether I understood your problem correctly.
