### ISSUE TITLE
Any plans for c++20?

### ISSUE THREAD

**Issue by alvarogalloc** [felixguendling/cista#165]
With the latest update of the most recent compilers, I think this library suits an update for the new language version

**Comment by felixguendling** [comment]
Thank you for your proposal. Which features from C++20 or C++23 do you mean? I think there's no value in rewriting the library for the sake of it. So there needs to be a significant gain in developer experience to justify the effort. I'm happily using cista in C++20 projects and didn't see any shortcomings that can now be fixed with C++20/23 features newly added to the language. I don't see me rewriting the libraries internals that are not "customer facing". An upgrade to C++20 would exclude users or require preprocessor checks/flags, so this requires caution.

**Comment by felixguendling** [comment]
In some places, cista already uses C++20 features if they're available:
https://github.com/felixguendling/cista/blob/1ab98b3a3b9b41b12788107325df3d7b7c49efa6/include/cista/containers/offset_ptr.h#L16-L26

I think one thing could be to add `operator<=>` support to cista's containers (conditionally, if C++20 is available). Anything else?
