### ISSUE TITLE
About Unreal Engine 5 Integration

### ISSUE THREAD

**Issue by ffreality** [felixguendling/cista#241]
I am trying to integrate `cista` to `Unreal Engine 5` to make faster and async (my async case is not using game thread) serialization. 

But I have an UE5 related problem. If integrated library has generic names like `check` or `verify`, these functions clash with UE5's functions and engine can't open. In order to solve that, we need to add a suffix or prefix.

For example I converted all `check` and verify to `cista_check` and `cista_verify` in your single header file.
I can send a pull request but can you give me where is your `check` and `verify` location ? Or should I look at every file ?

or can you do that ?

on the other hand, how can I build library as single header ? I can't see any single header or amalgamation related cmake option.

**Comment by felixguendling** [comment]
`cista::verify` and `cista::check` are both scoped into the `::cista` namespace so they definitely cannot clash with any other `check` or `verify` function. Only macros need to be prefixed, but this is already the case for every macro that ends up in the `cista.h` header file (`CISTA_*`): https://github.com/search?q=repo%3Afelixguendling%2Fcista%20%23define&type=code

If the problem is that you or UE5 has `verify` or `check` macros, it should be possible to either include `cista.h` before you include any UE5 related header (or your own header if these are your own macros). The other option would be to `#undef` the previously existing macros before including `cista.h`. I don't think this is a case where cista needs to be changed as cista is properly scoped in namespaces. If anything, it could make sense to specify `cista::verify` and `cista::check` to qualify the function.

So in case you have some compilation errors, can you please post the error message here?
