### ISSUE TITLE
How to serialize complicate struct?

### ISSUE THREAD

**Issue by linuxaged** [felixguendling/cista#57]
i have a struct `Group` like this:
```
struct vec3 {
	float x, y, z;
};

struct mat4 {
	float d[16];
};

struct Vertex {
	vec3 position;
	vec3 normal;
};

struct Mesh {
	cista::raw::vector<mat4> transforms;
	cista::raw::vector<Vertex> vertices;
};
using Meshes = cista::raw::vector<Mesh>;

struct Staging {
	int stepIndex;
	cista::raw::vector<float> distances;
	cista::raw::vector<vec3> translations;
	cista::raw::vector<vec3> rotations;
};
using Stagings = cista::raw::vector<Staging>;

struct Group {
	Meshes meshes;
	Stagings stagings;
}
```
have not found any similar example.

**Comment by felixguendling** [comment]
The only struct that requires custom serialization, deserialization (and hash if you want to use type hashing for versioning) is `mat4` because C arrays are not supported. But I would just use `cista::array<float, 16>` which has exactly the same properties as a C array (inside, it is a C array) but it's supported by Cista out of the box.

With this change, there is nothing you need to do. You can just call `serialize` and `deserialize`. I made an test case from your code:

https://github.com/felixguendling/cista/blob/2855eee72b0549aece1b684b9f0ccfb848a90475/test/mesh_test.cc#L13-L79
