### ISSUE TITLE
consider using wyhash instead of xxhash

### ISSUE THREAD

**Issue by halayli** [felixguendling/cista#58]
first off, cista rocks indeed! 

While skimming through the code I noticed xxhash usage. I suggest using wyhash instead as it performs better.

https://github.com/wangyi-fudan/wyhash

**Comment by felixguendling** [comment]
Thank you for your kind words and the link to wyhash.

Since the xxhash version in cista is xxh3, not xxh32/64 which is included in their benchmarks, I'm not sure which one is faster as this may also depend on the specific use case.

But I agree that it makes sense to include it into cista as an additional option. Currently, the cista uses FNV1a by default (download version) but when you use it as a CMake project, it is possible to use xxhash instead (add the `-DCISTA_XXH3=On` CMake option). So I plan to replace this option by a string (e.g. `CISTA_HASH=xxhash|wyhash|fnv1a`). However, I cannot promise this will happen any time soon. When it is easy to switch between hash implementations, everyone can quickly benchmark which one is the best for their use case just by changing the value of the CMake option.

**Comment by halayli** [comment]
Great! `CISTA_HASH=` is the most flexible. 

I missed the fact that FNV1a is the default. I thought xxhash was being used as the default and from my experience it doesn't perform well hence my suggestion.

Thanks!

**Comment by felixguendling** [comment]
Reopening as a reminder until this is implemented.
