### ISSUE TITLE
Unclear usage of `to_vec`

### ISSUE THREAD

**Issue by dm3** [felixguendling/cista#60]
Seems like `to_vec` is the go-to function for converting things into the `data::vector` type. However, `to_vec` only works with pointer types. E.g. can't convert `std::vector<double>` to `data::vector<double>`. Am I misunderstanding how it should be used?

**Comment by felixguendling** [comment]
Thank you for the hint. I think this was a mistake. Should be fixed now.

Usage should be simple:

https://github.com/felixguendling/cista/blob/800953ac76fdfe4ba2df95cc65045bd623b56d28/test/vector_test.cc#L51-L68

> Seems like to_vec is the go-to function for converting things into the data::vector type

Yes, you can use it like this. The basic idea was to have a concise and efficient way of writing a map operation and putting the result into a new vector (the version with `UnaryOperation`). From my experience, there this task is very common. But it turned out to be universally useful, even if you don't apply a transform but just want to switch to a vector (e.g. from a set or map).
