### ISSUE TITLE
buf target does not provide API access to get current offset/reset

### ISSUE THREAD

**Issue by dm3** [felixguendling/cista#61]
I've tried using the `buf` target as a mutable buffer which would store Cista-serialized data before writing to a binary file log. Works great, except I need to access the `curr_offset_` member to know the size of data serialized. I also need to reset the buffer after data has been flushed to file which means setting `curr_offset_ = 0`. 

Given that `buf` is a struct - is this by design or should an `offset()` and `reset()` methods be added?

**Comment by felixguendling** [comment]
I have removed `curr_offset_` in https://github.com/felixguendling/cista/commit/70deb80da413c7689dff16c6df3a7cefc6e16c16 because it is always the same value as `size()` now. Thus, you can use `size()` instead. I also added a `reset()` method which calls `resize(0)` on the underlying buffer which works for `std::vector<uint8_t>` as well as `cista::mmap`.
