### ISSUE TITLE
Is the output data compatible across other compilers and OS?

### ISSUE THREAD

**Issue by devildevilson** [felixguendling/cista#82]
Hello

First of all Cista is great, good work, you have my gratitude
I have a small dumb question. Im curious about the compatibility of the data produced by Cista. Is there any known limitations of being used in different environment?

**Comment by felixguendling** [comment]
In theory, I think it should work if you use standard layout, non-polymorphic aggregate types. Since the binary layout of structs in C++ is compatible to C and Cista only supports standard layout, non-polymorphic aggregate types out-of-the-box, this should be the same for all compilers. In all my tests (Little Endian <-> Big Endian, Windows <-> Linux <-> Mac OS X) this worked. However, I would test this carefully. Make sure to always use fixed width data types such as `uint32_t` instead of `unsigned` or `unsigned int`. This way, the binary layout should not differ between platforms **as long as the pointer width stays the same**.

I had a prototype working for the `offset` mode where 64bit programs can produce 32bit serialized data (with 32bit offsets). However, this is inconvenient because you cannot freely use 32bit offsets on a 64bit platform. You always need to make sure that a pointer is located max. 4GB apart from the value it points to. Thus, you need to allocate everything from the same memory buffer.

It would be much easier to use 64bit offsets everywhere (on 64bit and 32bit systems). Tell me if you need this. I can probably implement this in Cista without much overhead. The main part is switching the data type for offsets from `intptr_t` to `int64_t`in https://github.com/felixguendling/cista/blob/master/include/cista/offset_t.h

**Comment by devildevilson** [comment]
Im compiling my code against 64bit arch everywhere now, so It's good to see that the lib supports compatibility with gcc and msvc (my case). It's up to you to decide the changing in the offset.h file. If this changing isnt breaking the old code it would be appreciate to add some way to forse the 64bit offset (thru define may be?).

**Comment by felixguendling** [comment]
Please carefully check if this is true (compatibility) in your case and report any problems so I can look into them. However as I said for me it always worked as long as everything was 64bit. If you use padding bytes and zero them out explicitly, you can even check that the buffer contents match exactly (e.g. with `sha1sum` on the output).

Example: the struct alignment is 4 byte. So after the two 1 byte members (j, k), we need a padding to zero out the rest and avoid random bytes which would result in a random hash when using `sha1sum`.

```
struct test {
  uint32_t i;
  uint8_t j;
  uint8_t k;
  uint16_t padding{0};
};
```

**Comment by devildevilson** [comment]
Understood, thank you. I'll see if there is any problem.
