### ISSUE TITLE
Q: how to deal with C-arrays?

### ISSUE THREAD

**Issue by thekvs** [felixguendling/cista#84]
I my project I use one 3d-party closed-source library which I can't modify. That library uses some rather 'fat' C structures which also contain C-arrays. I'd like to serializes/deserialize these structures, but it looks like `cista` doesn't support C-arrays. Are there any plans to make such serialization possible? Or is it currently unsolvable task? Also any advise on how to deal with such situation will be highly appreciated.

**Comment by felixguendling** [comment]
Cista is quite flexible when dealing with 3rd-party structs. You can write a custom serialization/deserialization function for this specia data structure (but not for anything else - e.g. if you have a `cista::offset::vector<my_special_struct>` it is sufficient to write a serialization function for `my_special_struct`, Cista will take care of the rest).

An example of a very simple custom serialization/deserialization function can be seen here: https://github.com/felixguendling/cista/blob/master/test/custom_struct_test.cc

Cista already copies the data to the serialization buffer. If you don't have any pointers and don't deal with endian conversion (not necessary when staying on the same architecture), an empty custom serialization+deserialization function is sufficient. If you have any poiners, it gets more complicated because you need to ensure that the address you point to is also in the serializated buffer. Otherwise, you'll have a dangling pointer when deserializing.

If you need to serialize pointers, you can look at how a `cista::*::vector` is handled:

  - Serialization: https://github.com/felixguendling/cista/blob/master/include/cista/serialization.h#L159-L193
  - Deserialization: https://github.com/felixguendling/cista/blob/master/include/cista/serialization.h#L634-L664

Also the Wiki entry on custom serialization might be helpful for your: https://github.com/felixguendling/cista/wiki/Custom-(De-)Serialization-Functions

Feel free to ask further questions - ideally with a minimal example code snippet.

**Comment by thekvs** [comment]
Thanks a lot, empty custom serialization and deserialization functions solved my issue.
